export ROOT_PATH=$(pwd)
export DATA_PATH=DATA
export TMP_PATH=TMP
export SEQUENCES_PATH=$TMP_PATH/SEQUENCES.txt
export FFT_PATH=$TMP_PATH/FFT_60s_30s_BFPLOS
export PCA_TRANS_PATH=$TMP_PATH/PCA_TRANS
export FFT_PCA_PATH=$TMP_PATH/FFT_60s_30s_BFPLOS_PCA
export WINDOWED_COR_PATH=$TMP_PATH/COR_60s_30s
export NUMBER_FFT_FILES=128778
#export OMP_NUM_THREADS=4
mkdir -p $TMP_PATH
