export ROOT_PATH=$(pwd)
export DATA_PATH=DATA
export TMP_PATH=TMP
export SEQUENCES_PATH=$TMP_PATH/SEQUENCES.txt
export FFT_PATH=$TMP_PATH/FFT_60s_30s_BFPLOS
#export OMP_NUM_THREADS=4
mkdir -p $TMP_PATH
